### ISSUE TITLE
`BackHandler`s ignored when Appyx is hosted in androidx.navigation NavGraph 

### ISSUE THREAD

**Issue by steelahhh** [bumble-tech/appyx#102] opened 2022-08-25 09:19 UTC
Same issue as #60, but in this case it happens for any `NavModel`, not only nested

Repro project with more information: [AppyxNavComponentBugRepro](https://github.com/steelahhh/AppyxNavComponentBugRepro)

**Comment by LachlanMcKee** [comment] 2022-08-25 15:25
It looks like when onStop is called, all the other `OnBackPressedCallback` are removed, and when onStart occurs, they are readded. Because appyx is now at the bottom of the stack, it is invoked last.

This is why the fragment manager is now handling the back button instead.

This should be fairly easily fixed by also removing the `OnBackPressedCallback` and re-adding it the same way

**Comment by LachlanMcKee** [comment] 2022-08-25 15:33
@CherryPerry this might be of interest. I assume we will need to add a lifecycle listener into the HandleBackPress in some manner.

**Comment by CherryPerry** [comment] 2022-08-26 10:07
Thanks a lot for the reproduction project, saved a lot of time, the fix will be in the next release.

**Comment by steelahhh** [comment] 2022-08-29 08:45
Looks like there is slightly more to this – now a `OnBackPressedCallback` from a custom `BackPressHandler` plugin doesn't get invoked after `onStop`

Easiest way to repro this is in "Blocker" sample in sandbox, with same steps as before

**Comment by LachlanMcKee** [comment] 2022-08-29 08:58
@CherryPerry looks like there is an outstanding bug

**Comment by LachlanMcKee** [comment] 2022-08-29 08:59
Ah, you opened a different issue. Nevermind

**Closed by LachlanMcKee** 2022-08-29 08:59 UTC
Labels: bug
